### PR TITLE
feat: adding at_repl to packages

### PR DESCRIPTION
**Pull request by Xlin123**
### **- What I did**

- Created a Dart REPL. Published it onto pub.dev with atsign org  https://pub.dev/packages/at_repl 
- All of the instructions for installation/use are on pub.dev. 
- I retracted the latest version until the PR merges. 

### **- Verify**
Added more thorough testing to the project. Please let me know if I'm missing certain test cases. 

### **- Description for the changelog**
Created dart repl.

### CODE REVIEW

**Comment by JeremyTubongbanua** [comment]
After reading  https://pub.dev/packages/at_repl I tried installing it via locally

This is how I installed it locally which worked for me

```
cd packages/at_repl
dart pub global activate .  --source path
```

The instructions on how to download it locally on pub.dev did not work for me.

**Comment by JeremyTubongbanua** [comment]
I put in an incorrect atSign (that I do not have the keys to)

It did not read my keys

But it continued to put me in REPL

```
jeremytubongbanua@Jeremys-M2-Air ~ % at_repl -a @jeremy0 -r root.atsign.org:64 -v --no-enforceNamespace
Looking up secondary server address for @jeremy0 on root.atsign.org:64
Connecting...   Authentication failed: PathNotFoundException: Cannot open file, path = '/Users/jeremytubongbanua/.atsign/keys/@jeremy0_key.atKeys' (OS Error: No such file or directory, errno = 2)
Disconnected, atClient is null.
You don't need to include name spaces.
@jeremy0 scan
Unhandled exception:
Exception: AtClient is null for some reason...
#0      REPL.executeCommand (package:at_repl/src/at_repl.dart:42:7)
#1      main (file:///Users/jeremytubongbanua/GitHub/at_tools/packages/at_repl/bin/at_repl.dart:144:39)
<asynchronous suspension>
```

**Comment by JeremyTubongbanua** [comment]
**In /help** Typo?

```
regex (e.g. _scan test@alice.*)
```

Should it be `/scan` not `_scan` ?

**Comment by Xlin123** [comment]
there is a known bug related to [this ticket](https://github.com/atsign-foundation/at_client_sdk/issues/1057)
after that ticket is resolved, I'm planning to add at least _**a**_ test for shared_keys.

image

**Comment by Xlin123** [comment]
Need to wait until the at_client changes get pushed to pub.dev

**Comment by gkc** [comment]
> Need to wait until the at_client changes get pushed to pub.dev

Why?

**Comment by Xlin123** [comment]
I'm still getting the "Invalid or Corrupted Pad block" error for the shared_keys. I think it's fixed now, but it isn't in the latest version on pub so I'm just waiting.

Should I open the PR back up?

**Comment by gkc** [comment]
Can you test with the at_client_sdk trunk branch and verify the issue has been fixed please?

**Comment by gkc** [comment]
@Xlin123 Once you've verified that the issue has been fixed, please review & approve [this PR](https://github.com/atsign-foundation/at_client_sdk/pull/1070) so I can publish at_client v 3.0.62

**Review by gkc — APPROVED** [review]

**Comment by gkc** [comment]
Nice work @Xlin123

**Pull request merged**
